### ISSUE TITLE
Add example `pyproject.toml` using `poetry` instead of `setuptools`

### ISSUE THREAD

**Issue by FedericoStra** [FedericoStra/cython-package-example#1]
Take inspiration from:
- https://github.com/python-poetry/poetry/issues/11
- https://github.com/python-poetry/poetry/issues/137
- https://github.com/python-poetry/poetry/issues/1516
- https://stackoverflow.com/a/63679316
- https://github.com/ADicksonLab/geomm/tree/v0.1.7 (example of `build.py`)
- https://github.com/zoj613/htnorm (*more modern* example of `build.py`)
- https://github.com/decred/tinydecred/ (example of `build.py`)
- https://github.com/iamishalkin/cyrtd (Cython + Sphinx + poetry example)

**Comment by FedericoStra** [comment]
The state of the art best practices for packaging python modules with compiled extensions is just a desolate land of pain and suffering.

The crucial detail to defeat https://github.com/python-poetry/poetry/issues/1516 appears to be to require `setuptools` and `Cython` in the build system defined in `pyproject.toml`:
```toml
[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=57.0.0", "Cython>=0.29.27"]
build-backend = "poetry.core.masonry.api"
```
